"0": unknown
"1": ftpcontrol
"2": pop3
"3": smtp
"4": imap4
"5": dns
"6": ipp
"7": http
"8": mdns
"9": ntp
"10": netbios
"11": nfs
"12": ssdp
"13": bgp
"14": snmp
"15": xdmcp
"16": smb
"17": syslog
"18": dhcp
"19": postgres
"20": mysql
"21": hotmail
"22": directdownloadlink
"23": pop3s
"24": applejuice
"25": directconnect
"26": socrates
"27": coap
"28": vmware
"29": smtps
"30": filetopia
"31": ubntac2
"32": kontiki
"33": openft
"34": fasttrack
"35": gnutella
"36": edonkey
"37": bittorrent
"38": epp
"39": avi
"40": flash
"41": ocg
"42": mpeg
"43": quicktime
"44": realmedia
"45": windowsmedia
"46": mms
"47": xbox
"48": qq
"49": move
"50": rtsp
"51": imaps
"52": icecast
"53": pplive
"54": ppstream
"55": zattoo
"56": shoutcast
"57": sopcast
"58": tvants
"59": tvuplayer
"60": httpdownload
"61": qqlive
"62": thunder
"63": soulseek
"64": sslnocert
"65": irc
"66": ayiya
"67": unencryptedjabber
"68": msn
"69": oscar
"70": yahoo
"71": battlefield
"72": googleplus
"73": vrrp
"74": steam
"75": halflife2
"76": worldofwarcraft
"77": telnet
"78": stun
"79": ipsec
"80": gre
"81": icmp
"82": igmp
"83": egp
"84": sctp
"85": ospf
"86": ipinip
"87": rtp
"88": rdp
"89": vnc
"90": pcanywhere
"91": ssl
"92": ssh
"93": usenet
"94": mgcp
"95": iax
"96": tftp
"97": afp
"98": stealthnet
"99": aimini
"100": sip
"101": truphone
"102": icmpv6
"103": dhcpv6
"104": armagetron
"105": crossfire
"106": dofus
"107": fiesta
"108": florensia
"109": guildwars
"110": httpactivesync
"111": kerberos
"112": ldap
"113": maplestory
"114": mssqltds
"115": pptp
"116": warcraft3
"117": worldofkungfu
"118": slack
"119": facebook
"120": twitter
"121": dropbox
"122": gmail
"123": googlemaps
"124": youtube
"125": skype
"126": google
"127": dcerpc
"128": netflow
"129": sflow
"130": httpconnect
"131": httpproxy
"132": citrix
"133": netflix
"134": lastfm
"135": waze
"136": youtubeupload
"137": icq
"138": checkmk
"139": citrixonline
"140": apple
"141": webex
"142": whatsapp
"143": appleicloud
"144": viber
"145": appleitunes
"146": radius
"147": windowsupdate
"148": teamviewer
"149": tuenti
"150": lotusnotes
"151": sap
"152": gtp
"153": upnp
"154": llmnr
"155": remotescan
"156": spotify
"157": webm
"158": h323
"159": openvpn
"160": noe
"161": ciscovpn
"162": teamspeak
"163": tor
"164": skinny
"165": rtcp
"166": rsync
"167": oracle
"168": corba
"169": ubuntuone
"170": whoisdas
"171": collectd
"172": socks
"173": nintendo
"174": rtmp
"175": ftpdata
"176": wikipedia
"177": zmq
"178": amazon
"179": ebay
"180": cnn
"181": megaco
"182": redis
"183": pando
"184": vhua
"185": telegram
"186": vevo
"187": pandora
"188": quic
"189": whatsappvoice
"190": eaq
"191": ookla
"192": amqp
"193": kakaotalk
"194": kakaotalkvoice
"195": twitch
"196": quickplay
"197": wechat
"198": mpegts
"199": snapchat
"200": sina
"201": hangout
"202": iflix
"203": github
"204": bjnp
"205": 1kxun
"206": iqiyi
"207": smpp
"208": dnscrypt
"209": tinc
"210": deezer
"211": instagram
"212": microsoft
"213": starcraft
"214": teredo
"215": hotspotshield
"216": hep
"217": googledrive
"218": ocs
"219": office365
"220": cloudflare
"221": msonedrive
"222": mqtt
"223": rx
"224": applestore
"225": opendns
"226": git
"227": drda
"228": playstore
"229": someip
"230": fix
"231": playstation
"232": pastebin
"233": linkedin
"234": soundcloud
"235": csgo
"236": lisp
"237": diameter
"238": applepush
"239": googleservices
"240": amazonvideo
"241": googledocs
"242": whatsappvideo
